### ISSUE TITLE
point station-name not imported correctly into scrap

### ISSUE THREAD

**Issue by CaverBruce** [daem-on/wtherion#2]
When importing an existing th2 file, one point station-name was imported as point dimensions.  This seems to be a one-off.  Other point station-names are OK.
![image](https://user-images.githubusercontent.com/19825868/152748903-13fa7b9c-5bbf-4bce-aae4-ec3c4bd99fae.png)

![image](https://user-images.githubusercontent.com/19825868/152748851-40433412-711c-4c6d-9ca9-0fccd0af7a93.png)

**Comment by daem-on** [comment]
I'm quite sure this is was a bug not in the importer, but the settings panel. The panel (for points, for now) only allows types to be picked from the list, and the list contained `stationname` instead of `station-name` because of a mistake I made.
I think none of the other points would have worked if you were to look at their settings panel.
